import { useEffect, useState } from "react";
import html2canvas from "html2canvas";

const ExportSqlModal = ({ onClose, erdCanvasId = "erd-canvas" }) => {
  const [dbms, setDbms] = useState("postgres");

  useEffect(() => {
    const handleKey = (e) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [onClose]);

  const fakeSqlMap = {
    postgres: "-- PostgreSQL용 CREATE TABLE 예시\nCREATE TABLE users (\n  id SERIAL PRIMARY KEY,\n  name VARCHAR(100) NOT NULL\n);",
    mysql: "-- MySQL용 CREATE TABLE 예시\nCREATE TABLE users (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  name VARCHAR(100) NOT NULL\n);",
    oracle: "-- Oracle용 CREATE TABLE 예시\nCREATE TABLE users (\n  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,\n  name VARCHAR2(100) NOT NULL\n);",
  };

  const handleImageDownload = async () => {
    const canvasElement = document.getElementById(erdCanvasId);
    if (!canvasElement) {
      alert("❌ 캔버스 영역을 찾을 수 없습니다.");
      return;
    }

    const tableEls = canvasElement.querySelectorAll(".erd-table-box");
    if (!tableEls.length) {
      alert("📭 테이블이 없습니다.");
      return;
    }

    // 🔄 모달을 화면 밖으로 이동 (숨김 대신 깜빡임 제거용)
    const modal = document.getElementById("export-sql-modal");
    const originalStyle = modal?.style.cssText;

    if (modal) {
      modal.style.position = "absolute";
      modal.style.left = "-9999px";
      modal.style.top = "-9999px";
    }

    await new Promise((r) => setTimeout(r, 100));

    // 📐 테이블 위치 계산
    let minX = Infinity,
      minY = Infinity,
      maxX = -Infinity,
      maxY = -Infinity;
    tableEls.forEach((el) => {
      const rect = el.getBoundingClientRect();
      minX = Math.min(minX, rect.left);
      minY = Math.min(minY, rect.top);
      maxX = Math.max(maxX, rect.right);
      maxY = Math.max(maxY, rect.bottom);
    });

    minX += window.scrollX;
    maxX += window.scrollX;
    minY += window.scrollY;
    maxY += window.scrollY;

    const width = maxX - minX;
    const height = maxY - minY;

    try {
      const fullCanvas = await html2canvas(document.body, {
        backgroundColor: null,
        useCORS: true,
        scale: 2,
      });

      const croppedCanvas = document.createElement("canvas");
      croppedCanvas.width = width * 2;
      croppedCanvas.height = height * 2;
      const ctx = croppedCanvas.getContext("2d");

      ctx.drawImage(
        fullCanvas,
        minX * 2,
        minY * 2,
        width * 2,
        height * 2,
        0,
        0,
        width * 2,
        height * 2
      );

      const link = document.createElement("a");
      link.href = croppedCanvas.toDataURL("image/png");
      link.download = "erd_tables_only.png";
      link.click();
    } catch (err) {
      console.error("이미지 다운로드 실패:", err);
      alert("❌ 이미지 다운로드 중 오류가 발생했습니다.");
    } finally {
      // 🔙 모달 원위치 복원
      if (modal && originalStyle !== undefined) {
        modal.style.cssText = originalStyle;
      }
    }
  };

  return (
    <div
      id="export-sql-modal"
      className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center"
    >
      <div className="bg-[#1f1f2b] text-white rounded-xl shadow-xl p-6 relative w-[420px] max-w-full border border-gray-700">
        <button
          onClick={onClose}
          className="absolute top-2 right-3 text-gray-400 hover:text-white text-xl"
        >
          ×
        </button>

        <h2 className="text-xl font-semibold mb-4">📦 내보내기</h2>

        <div className="space-y-2 mb-3">
          <label className="text-sm font-medium">DBMS 선택</label>
          <select
            className="w-full border border-gray-600 bg-[#2a2d3a] text-white px-3 py-2 rounded"
            value={dbms}
            onChange={(e) => setDbms(e.target.value)}
          >
            <option value="postgres">PostgreSQL</option>
            <option value="mysql">MySQL</option>
            <option value="oracle">Oracle</option>
          </select>
        </div>

        <pre className="bg-[#2a2d3a] text-gray-200 text-xs p-3 rounded h-[120px] overflow-auto border border-gray-600">
          {fakeSqlMap[dbms]}
        </pre>

        <div className="mt-4 flex flex-col gap-2">
          <button
            disabled
            className="w-full bg-gray-600 text-white py-2 rounded cursor-not-allowed"
          >
            SQL 다운로드 (준비 중)
          </button>

          <button
            onClick={handleImageDownload}
            className="w-full bg-green-600 text-white py-2 rounded hover:bg-green-700"
          >
            이미지 다운로드
          </button>
        </div>
      </div>
    </div>
  );
};

export default ExportSqlModal;
